apiVersion: v1
kind: Service
metadata:
  name: blockchain-monitor-service
  labels:
    app: blockchain-monitor
spec:
  type: ClusterIP
  selector:
    app: blockchain-monitor
  ports:
  - port: 80
    targetPort: 9999
    protocol: TCP
    name: http
  - port: 9999
    targetPort: 9999
    protocol: TCP
    name: monitor