// Regression tests for the build/packaging configuration touched by this PR:
// `.gitignore`, the committed `Cargo.lock`, and the `Dockerfile`.
//
// These are plain file-content checks (no cargo/docker invocation), since the
// changes are about *what gets committed and how the image is built* rather
// than runtime behavior covered by the unit tests in `src/main.rs`.

use std::fs;
use std::path::Path;

fn manifest_dir() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
}

#[test]
fn gitignore_no_longer_ignores_cargo_lock() {
    // Cargo.lock must now be committed (required for `cargo build --locked`
    // in the Dockerfile) — regression guard against re-adding a bare
    // "Cargo.lock" ignore rule.
    let contents = fs::read_to_string(manifest_dir().join(".gitignore"))
        .expect("failed to read .gitignore");

    let has_bare_cargo_lock_rule = contents
        .lines()
        .map(str::trim)
        .any(|line| line == "Cargo.lock");

    assert!(
        !has_bare_cargo_lock_rule,
        ".gitignore must not ignore Cargo.lock, otherwise the Dockerfile's \
         `cargo build --locked` step would silently lose its pinned lockfile"
    );
}

#[test]
fn gitignore_ignores_claude_harness_state() {
    let contents = fs::read_to_string(manifest_dir().join(".gitignore"))
        .expect("failed to read .gitignore");

    assert!(
        contents.lines().map(str::trim).any(|line| line == ".claude/"),
        ".gitignore should ignore the transient .claude/ harness state directory"
    );
}

#[test]
fn gitignore_still_ignores_target_dir() {
    let contents = fs::read_to_string(manifest_dir().join(".gitignore"))
        .expect("failed to read .gitignore");

    assert!(
        contents.lines().map(str::trim).any(|line| line == "/target/"),
        ".gitignore should still ignore the Rust build output directory"
    );
}

#[test]
fn cargo_lock_is_committed_and_pins_this_package() {
    let path = manifest_dir().join("Cargo.lock");
    assert!(
        path.exists(),
        "Cargo.lock must be committed to the repository for reproducible, --locked builds"
    );

    let contents = fs::read_to_string(&path).expect("failed to read Cargo.lock");

    assert!(
        contents.contains("name = \"monitor\""),
        "Cargo.lock should contain a locked entry for the `monitor` package"
    );
    assert!(
        contents.contains("This file is automatically @generated by Cargo"),
        "Cargo.lock should be a genuine Cargo-generated lockfile"
    );
}

#[test]
fn dockerfile_copies_and_builds_against_the_committed_lockfile() {
    let contents = fs::read_to_string(manifest_dir().join("Dockerfile"))
        .expect("failed to read Dockerfile");

    assert!(
        contents.contains("COPY Cargo.toml Cargo.lock"),
        "Dockerfile must copy Cargo.lock alongside Cargo.toml for dependency caching"
    );
    assert!(
        contents.contains("cargo build --release --locked"),
        "Dockerfile must build with --locked so the image matches the committed Cargo.lock \
         exactly (MSRV-compatible dependency pinning)"
    );
}